In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data=pd.read_csv('.\ex1data2.txt',header=None,names=['Size', 'Bedrooms', 'Price'])
data.head()

Size  Bedrooms   Price
0  2104         3  399900
1  1600         3  329900
2  2400         3  369000
3  1416         2  232000
4  3000         4  539900

In [3]:
X=data.iloc[:,:-1].values
y=data.iloc[:,-1:].values

In [4]:
X

array([[2104,    3],
       [1600,    3],
       [2400,    3],
       [1416,    2],
       [3000,    4],
       [1985,    4],
       [1534,    3],
       [1427,    3],
       [1380,    3],
       [1494,    3],
       [1940,    4],
       [2000,    3],
       [1890,    3],
       [4478,    5],
       [1268,    3],
       [2300,    4],
       [1320,    2],
       [1236,    3],
       [2609,    4],
       [3031,    4],
       [1767,    3],
       [1888,    2],
       [1604,    3],
       [1962,    4],
       [3890,    3],
       [1100,    3],
       [1458,    3],
       [2526,    3],
       [2200,    3],
       [2637,    3],
       [1839,    2],
       [1000,    1],
       [2040,    4],
       [3137,    3],
       [1811,    4],
       [1437,    3],
       [1239,    3],
       [2132,    4],
       [4215,    4],
       [2162,    4],
       [1664,    2],
       [2238,    3],
       [2567,    4],
       [1200,    3],
       [ 852,    2],
       [1852,    4],
       [1203,    3]], dtype=int64)

In [6]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X)
y=scaler.fit_transform(y)

C:\Users\Himanshu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


In [9]:
from sklearn.linear_model import LinearRegression
regressor1=LinearRegression()
regressor1.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [14]:
y_pred=regressor1.predict(X)
y_new=scaler.inverse_transform(y_pred)
y_new.astype(int)

array([[356283],
       [286120],
       [397489],
       [269244],
       [472277],
       [330979],
       [276933],
       [262037],
       [255494],
       [271364],
       [324714],
       [341805],
       [326492],
       [669293],
       [239902],
       [374830],
       [255879],
       [235448],
       [417846],
       [476593],
       [309369],
       [334951],
       [286677],
       [327777],
       [604913],
       [216515],
       [266353],
       [415030],
       [369647],
       [430482],
       [328130],
       [220070],
       [338635],
       [500087],
       [306756],
       [263429],
       [235865],
       [351442],
       [641418],
       [355619],
       [303768],
       [374937],
       [411999],
       [230436],
       [190729],
       [312464],
       [230854]])

In [13]:
regressor1.predict(np.array([1650,3]))

C:\Users\Himanshu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[  1.80909542e+08]])

In [28]:
regressor1.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': 1, 'normalize': False}